Adapters & Client refactor
ArizenHQ/sidekiq_flow pull request #23
Opened 2021-03-02 14:23 UTC by VIGER-Valentin

Creation of backend adapters
New Adapter : legacy_storage that contains the existing Client logic
Client now interfaces adapters

2021-03-05 18:08 UTC, franee requested changes
Please also update the gem version.

2021-03-05 18:08 UTC, franee commented on lib/sidekiq_flow/client.rb
> +        adapters.last.find_workflow_keys(pattern=workflow_key_pattern)
pass only pattern here.

2021-03-08 09:57 UTC, VIGER-Valentin commented on lib/sidekiq_flow/client.rb
> +        adapters.last.find_workflow_keys(pattern=workflow_key_pattern)
Done

2021-03-08 10:19 UTC, franee approved these changes

2021-03-08 10:19 UTC, franee commented on lib/sidekiq_flow/adapters/legacy_storage.rb
> +
nit, pls configure your editor to remove extra blank lines, or just run `rubocop --fix <path to your file>` before committing.

2023-10-18 08:20 UTC, closed without merging